import { DefaultTheme } from "styled-components";
import Color from "color";

export const DarkTheme: DefaultTheme = {
  colors: {
    font: {
      body: Color.rgb(255, 255, 255, 0.9),
      subdued: Color.rgb(255, 255, 255, 0.6),
      inverted: Color.rgb(0, 0, 0, 0.9),
    },
    background: {
      0: Color("#141414"),
      1: Color("#1a1a1a"),
      2: Color("#202020"),
      3: Color("#262626"),
      4: Color("#2c2c2c"),
      5: Color("#313131"),
    },
    inverted: {
      0: Color("#ebebeb"),
      1: Color("#e5e5e5"),
      2: Color("#dfdfdf"),
      3: Color("#d9d9d9"),
      4: Color("#d3d3d3"),
      5: Color("#cecece"),
    },
    shadow: {
      dark: Color.rgb(0, 0, 0, 0.9),
      light: Color.rgb(100, 100, 100, 0.9),
    },
    placeholder: Color.rgb(255, 255, 255, 0.1),
    popover: Color.rgb(80, 80, 80),
    error: Color("#de0017"),
    gold: Color("#b29b5c"),
    blue: Color("#6495ed"),
    pink: Color("#ed6495"),
    green: Color("#00853e"),
    white: Color("#fff"),
    black: Color("#010101"),
  },
  font: {
    size: {
      heading: "17px",
      subheading: "13px",
      extrasmall: "9px",
      small: "12px",
      basesmall: "14px",
      base: "15px",
      baselarge: "16px",
      large: "18px",
      extralarge: "22px",
      metasmall: "13px",
      metamedium: "15px",
      metalarge: "18px",
      displaysmall: "24px",
      displaylarge: "32px",
    },
    height: {
      heading: "19px",
      subheading: "15px",
      extrasmall: "10px",
      small: "13px",
      basesmall: "16px",
      base: "17px",
      baselarge: "18px",
      large: "20px",
      extralarge: "24px",
      metasmall: "17px",
      metamedium: "21px",
      metalarge: "25px",
      displaysmall: "28px",
      displaylarge: "40px",
    },
  },
  icon: {
    extrasmall: "11px",
    small: "15px",
    basesmall: "19px",
    base: "23px",
    baselarge: "27px",
    large: "31px",
    extralarge: "39px",
  },
  avatar: {
    extrasmall: "32px",
    small: "36px",
    basesmall: "40px",
    base: "44px",
    baselarge: "48px",
    large: "52px",
    extralarge: "72px",
  },
  border: {
    radius: {
      none: "0",
      smallest: "2px",
      small: "4px",
      base: "6px",
      large: "8px",
      largest: "10px",
      full: "100%",
    },
    width: {
      none: "0",
      smallest: "1px",
      small: "2px",
      base: "3px",
      large: "4px",
      largest: "5px",
    },
  },
  spacing: {
    none: "0",
    extratight: "4px",
    tight: "8px",
    basetight: "12px",
    base: "16px",
    baseloose: "20px",
    loose: "32px",
    extraloose: "40px",
  },
  duration: {
    instant: "0ms",
    fastest: "100ms",
    faster: "200ms",
    fast: "300ms",
    base: "500ms",
    slow: "700ms",
    slower: "1s",
    slowest: "2s",
  },
};

export const LightTheme: DefaultTheme = DarkTheme;
